import Footer from './components/footer/Footer';
import Navbar from './components/navbar/Navbar';
import { AppProvider } from './context/context';
import AuthProvider from './context/AuthProvider';
import './globals.css';
import { NAVBAR_HEIGHT } from './utils/constants';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang='en'>
      <body>
        <AuthProvider>
          <AppProvider>
            <Navbar session={session} />
            <div className='flex flex-col justify-between min-h-[calc(100vh-66px)]'>
              {children}
              <Footer />
            </div>
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
